{"data":[{"id":"I_kwDOGa-rA86PMYc-","closed":true,"title":"inference.py is not working with large dataset.","createdAt":"2024-07-11T06:43:23Z","url":"https://github.com/mk-minchul/AdaFace/issues/154","number":154,"assignees":{"nodes":[]},"repository":{"name":"AdaFace","url":"https://github.com/mk-minchul/AdaFace","owner":{"login":"mk-minchul","avatarUrl":"https://avatars.githubusercontent.com/u/18522020?u=aca0416acd397004453714790c36eb2e99e22c31&v=4","url":"https://github.com/mk-minchul"}}},{"id":"I_kwDOKkJaos6MGs8k","closed":true,"title":"[BUG]: A small spelling mistake","createdAt":"2024-06-13T08:49:04Z","url":"https://github.com/sotopia-lab/sotopia/issues/93","number":93,"assignees":{"nodes":[]},"repository":{"name":"sotopia","url":"https://github.com/sotopia-lab/sotopia","owner":{"login":"sotopia-lab","avatarUrl":"https://avatars.githubusercontent.com/u/144055741?v=4","url":"https://github.com/sotopia-lab"}}}],"open":0,"closed":2,"totalCount":2}